version: '2.4'

services:
  orderer:
    container_name: secdt-fabric_orderer_1
    image: hyperledger/fabric-orderer:2.5
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=file
      - ORDERER_GENERAL_BOOTSTRAPFILE=/var/hyperledger/orderer/genesis.block
      - ORDERER_CHANNELPARTICIPATION_ENABLED=false
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:9443
      - ORDERER_ADMIN_TLS_ENABLED=false
      - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:8443
      - ORDERER_METRICS_PROVIDER=disabled
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    ports:
      - 7050:7050
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/genesis.block
      - ./crypto-config/ordererOrganizations/secdt.com/orderers/${ORDERER_HOSTNAME}.secdt.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/secdt.com/orderers/${ORDERER_HOSTNAME}.secdt.com/tls:/var/hyperledger/orderer/tls
      - secdt-fabric_orderer-data:/var/hyperledger/production/orderer
    restart: unless-stopped

volumes:
  secdt-fabric_orderer-data:
